server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files \ \/ /index.html;
    }
    
    location /api/ {
        resolver kube-dns.kube-system.svc.cluster.local valid=5s;
        proxy_pass http://backend-service.todo-app.svc.cluster.local:5000/;
        proxy_http_version 1.1;
        proxy_set_header Host \System.Management.Automation.Internal.Host.InternalHost;
    }
}
